"""
Evaluate DebateFloor policies through the live OpenEnv HTTP API.

This is intentionally lightweight: it proves that reward/eval evidence can be
generated by driving /reset and /step, not by importing server internals.

Usage:
  python scripts/evaluate_http_rollouts.py --base-url http://localhost:7860
  python scripts/evaluate_http_rollouts.py --base-url https://aniketasla-debatefloor.hf.space
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from statistics import mean
from typing import Any, Callable, Dict, List

import requests

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from inference_debatefloor import STRATEGIES, TASK_CONFIG, DebateFloorClient


TASKS = list(TASK_CONFIG.keys())
REPORT_JSON = Path("reports/http_rollout_eval.json")
REPORT_MD = Path("reports/http_rollout_eval.md")


def naive_high_actions(_client: DebateFloorClient, obs: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Overconfident baseline: decide immediately with HIGH confidence."""
    task_id = obs.get("observation", {}).get("task_id", "clean_claim")
    decision = {
        "clean_claim": "approve_claim",
        "contradictory_claim": "approve_claim",
        "distribution_shift_claim": "approve_claim",
    }.get(task_id, "approve_claim")
    return [
        {
            "action_type": decision,
            "confidence": "HIGH",
            "parameters": {"reason": "Immediate high-confidence baseline decision."},
            "reasoning": "No investigation performed.",
        }
    ]


POLICIES: Dict[str, Callable[[DebateFloorClient, Dict[str, Any]], List[Dict[str, Any]]]] = {
    "naive_high_no_investigation": naive_high_actions,
    "calibrated_scripted_investigator": lambda client, obs: STRATEGIES[
        obs.get("observation", {}).get("task_id", "clean_claim")
    ](client, obs),
}


def run_policy(
    base_url: str,
    policy_name: str,
    policy_fn: Callable[[DebateFloorClient, Dict[str, Any]], List[Dict[str, Any]]],
    task_id: str,
    seed: int,
) -> Dict[str, Any]:
    client = DebateFloorClient(base_url)
    obs = client.reset(task_id=task_id, seed=seed)
    actions = policy_fn(client, obs)
    final: Dict[str, Any] = obs
    steps = 0

    for action in actions:
        steps += 1
        final = client.step(action)
        if final.get("done"):
            break

    observation = final.get("observation", {})
    metadata = observation.get("metadata", {})
    breakdown = observation.get("reward_breakdown", {})
    action_history = observation.get("action_history", [])
    final_action = action_history[-1].get("action_type") if action_history else None
    calibration = metadata.get("calibration_score")

    return {
        "policy": policy_name,
        "task_id": task_id,
        "seed": seed,
        "steps": steps,
        "done": bool(final.get("done")),
        "reward": float(final.get("reward", 0.0)),
        "final_decision": final_action,
        "agent_confidence": metadata.get("agent_confidence"),
        "calibration_score": calibration,
        "decision_accuracy": breakdown.get("decision_accuracy"),
        "fraud_detection_score": breakdown.get("fraud_detection_score"),
        "evidence_quality_score": breakdown.get("evidence_quality_score"),
    }


def write_reports(rows: List[Dict[str, Any]], base_url: str) -> None:
    REPORT_JSON.parent.mkdir(parents=True, exist_ok=True)
    REPORT_JSON.write_text(json.dumps({"base_url": base_url, "rows": rows}, indent=2), encoding="utf-8")

    by_policy: Dict[str, List[Dict[str, Any]]] = {}
    for row in rows:
        by_policy.setdefault(row["policy"], []).append(row)

    lines = [
        "# DebateFloor HTTP Rollout Evaluation",
        "",
        f"Base URL: `{base_url}`",
        "",
        "| Policy | Episodes | Mean reward | Mean calibration | Success rate |",
        "|---|---:|---:|---:|---:|",
    ]
    for policy, policy_rows in by_policy.items():
        rewards = [r["reward"] for r in policy_rows]
        calibrations = [
            r["calibration_score"] for r in policy_rows if r["calibration_score"] is not None
        ]
        successes = [
            1.0 if r.get("done") and (r.get("decision_accuracy") == 1.0) else 0.0
            for r in policy_rows
        ]
        lines.append(
            f"| {policy} | {len(policy_rows)} | {mean(rewards):.3f} | "
            f"{mean(calibrations) if calibrations else 0.0:.3f} | {mean(successes):.2%} |"
        )

    lines.extend(["", "## Per-Episode Rows", ""])
    lines.append("| Policy | Task | Seed | Reward | Calibration | Confidence | Steps |")
    lines.append("|---|---|---:|---:|---:|---|---:|")
    for row in rows:
        lines.append(
            f"| {row['policy']} | {row['task_id']} | {row['seed']} | "
            f"{row['reward']:.3f} | {row['calibration_score']} | "
            f"{row['agent_confidence']} | {row['steps']} |"
        )

    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {REPORT_JSON}")
    print(f"Wrote {REPORT_MD}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", default="http://localhost:7860")
    parser.add_argument("--seeds", type=int, nargs="+", default=[42, 43, 44])
    args = parser.parse_args()

    health = requests.get(f"{args.base_url.rstrip('/')}/health", timeout=10)
    health.raise_for_status()

    rows: List[Dict[str, Any]] = []
    for policy_name, policy_fn in POLICIES.items():
        for task_id in TASKS:
            for seed in args.seeds:
                rows.append(run_policy(args.base_url, policy_name, policy_fn, task_id, seed))

    write_reports(rows, args.base_url)


if __name__ == "__main__":
    main()
